package com.aspen.aspensc;

/**
 * Created by rfrench on 1/20/2015.
 *
 * CREATE TABLE [dbo].[IC_Products](
 [ProductKey] [int] NOT NULL,
 [ProductCode] [nvarchar](12) NOT NULL,
 [ProductSequence] [int] NOT NULL,
 [WarehouseCode] [int] NULL,
 [Description1] [nvarchar](40) NOT NULL,
 [Description2] [nvarchar](40) NULL,
 [ProductCategoryCode] [int] NULL,
 [AlphaName] [nvarchar](12) NOT NULL,
 [SelectionCode] [nvarchar](16) NULL,
 [ProcessCode] [int] NULL,
 [ProductClassificationCode] [int] NULL,
 [FreightDistributionCode] [int] NULL,
 [BrandCode] [int] NULL,
 [IngredientsCode] [int] NULL,
 [TareCode_Pack] [int] NULL,
 [TareCode_Case] [int] NULL,
 [StockLocation] [nvarchar](10) NULL,
 [Inventory] [bit] NOT NULL,
 [LotInventory] [bit] NOT NULL,
 [SlotKey_Picking] [int] NULL,
 [SlotKey_Backstock] [int] NULL,
 [Discontinued] [smallint] NULL,
 [CatchweightItem] [bit] NOT NULL,
 [SpecialOrder] [bit] NOT NULL,
 [Backorder] [bit] NOT NULL,
 [TrackLotTemperature] [bit] NOT NULL,
 [SalesTax] [bit] NOT NULL,
 [CostGroupStatus] [smallint] NULL,
 [ProductKey_CostMaster] [int] NULL,
 [UnitOfMeasure_Stk] [nvarchar](3) NOT NULL,
 [UnitOfMeasure_Alt] [nvarchar](3) NULL,
 [UnitOfMeasure_Cwt] [nvarchar](3) NULL,
 [UnitOfMeasure_Prc] [nvarchar](3) NULL,
 [UnitOfMeasure_SellBy] [nvarchar](3) NULL,
 [UnitOfMeasure_OrderBy] [nvarchar](3) NULL,
 [DepleteGroupStatus] [smallint] NULL,
 [ProductKey_DepleteMaster] [int] NULL,
 [DepleteWholeUnitsFlag] [smallint] NULL,
 [DepleteConversion] [real] NOT NULL,
 [WeightConversion] [real] NOT NULL,
 [CatchweightVariance] [real] NOT NULL,
 [CAB_Commission] [money] NOT NULL,
 [CriticalQuantity] [money] NOT NULL,
 [ReorderQuantity] [money] NOT NULL,
 [ReceiptDelay] [smallint] NOT NULL,
 [NumberOfDays_SellBy] [smallint] NOT NULL,
 [NumberOfDays_Expiration] [smallint] NOT NULL,
 [MinimumShipWeight] [money] NOT NULL,
 [MaximumShipWeight] [money] NOT NULL,
 [MinimumTareWeight] [money] NOT NULL,
 [MaximumTareWeight] [money] NOT NULL,
 [OtherTareWeight] [money] NOT NULL,
 [OverrideQuantity_Stk] [money] NOT NULL,
 [OverrideQuantity_Alt] [money] NOT NULL,
 [PrintPalletLabels] [bit] NOT NULL,
 [CasesPerPallet] [int] NOT NULL,
 [PrintPackageLabels] [bit] NOT NULL,
 [PackagesPerCase] [int] NOT NULL,
 [LabelDateLiteral] [nvarchar](14) NULL,
 [LabelDateOffset] [int] NOT NULL,
 [LabelFormat] [int] NULL,
 [PackLabelFormat] [int] NULL,
 [NutritionFactCode] [int] NULL,
 [AllowMultipleScan] [bit] NOT NULL,
 [Comment1] [nvarchar](40) NULL,
 [Comment2] [nvarchar](40) NULL,
 [LevelTypeFlag] [smallint] NULL,
 [TotallerFlag] [smallint] NULL,
 [USDA_Flag] [bit] NOT NULL,
 [USDA_ProductType] [smallint] NULL,
 [USDA_ClassCode] [smallint] NULL,
 [USDA_Refrigeration] [smallint] NULL,
 [USDA_Classification] [smallint] NULL,
 [USDA_Trim] [smallint] NULL,
 [USDA_WeightType] [smallint] NULL,
 [USDA_IMPSCode] [nvarchar](4) NULL,
 [USDA_BrandedYieldBeef] [smallint] NULL,
 [USDA_PorkClassCode] [smallint] NULL,
 [USDA_PorkRefrigeration] [smallint] NULL,
 [USDA_PorkDeliveryUnit] [smallint] NULL,
 [HighPriceWarnFlag] [bit] NOT NULL,
 [HighPriceWarnBase] [money] NOT NULL,
 [HighPriceWarnAddOnType] [smallint] NULL,
 [HighPriceWarnAddOnAmount] [real] NOT NULL,
 [LowPriceWarnFlag] [bit] NOT NULL,
 [LowPriceWarnBase] [money] NOT NULL,
 [LowPriceWarnAddOnType] [smallint] NULL,
 [LowPriceWarnAddOnAmount] [real] NOT NULL,
 [CustomLotFieldGroupCode] [int] NULL,
 [FillVariance] [real] NOT NULL,
 [PO_PriceVariance] [real] NOT NULL,
 [PO_ReceiptVariance] [real] NOT NULL,
 [DateOpened] [smalldatetime] NULL,
 [EstimatedDailyDemand] [money] NOT NULL,
 [SafetyStock] [money] NOT NULL,
 [SafetyStockDays] [smallint] NOT NULL,
 [ProductSeasonCode] [int] NULL,
 [Notes] [ntext] NULL,
 [Ingredients] [ntext] NULL,
 [OrderEntryInventoryThreshold] [money] NOT NULL,
 [OrderEntryInventoryThresholdUM] [smallint] NULL,
 [NearEmptySlotThreshold] [money] NOT NULL,
 [NearEmptySlotThreshold_QtyType] [smallint] NOT NULL,
 [MaterialClassCode] [int] NULL,
 [LotHoldCode] [int] NULL,
 [UserID_LastModifiedBy] [nvarchar](20) NULL,
 [LastModifiedDate] [datetime] NULL,
 [PacksPerCase] [int] NOT NULL,
 [PackSize] [money] NOT NULL,
 [PackSizeUnit] [nvarchar](3) NULL,
 [InnerPacksPerPack] [int] NOT NULL,
 [InnerPackSize] [money] NOT NULL,
 [InnerPackSizeUnit] [nvarchar](3) NULL,
 [ProductFolder] [nvarchar](200) NULL,
 [USDA_Quality] [smallint] NULL,
 [IgnoreOEAvailWarning] [bit] NOT NULL,
 [CommittedDaysOverride] [smallint] NULL,
 */
public class Products {



}
